# Etapa 1: Build del proyecto (instala dependencias)
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Etapa 2: Runtime minimal
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3001

CMD ["npm", "start"]